server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.93.83/finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: Ysj245913@.
  data:
    redis:
      host: 49.233.93.83
      port: 6379
      connectTimeout: 2000ms
# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 用于打印框架生成的sql语句，便于调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  # 扁平化展示对象参数
  default-flat-param-object: true

logging:
  level:
    org.springframework.security: DEBUG

# jwt 配置（建议生产用 Base64 随机字节；示例是 256-bit 的 Base64）
jwt:
  secret: w9FJmkF3x3+QbHqHZq2lLVdcmRbth9+PpMNeWjVlzGk=
  expire: 7d
  header: Authorization        # 读取 Token 的请求头







